Requirement already satisfied: python-dateutil in c:\users\gis\anaconda3\lib\site-packages (1.5)
